import Image from "next/image";
import { notFound } from "next/navigation";
import { AdminShell, PageHeader, StatusBadge } from "@toms/admin-ui";
import { formatCurrencyMinor } from "@toms/config";
import { TourPublishActions } from "@/components/tour-publish-actions";
import { getAdminJson } from "@/lib/api";
type Tour={id:string;name:string;slug:string;summary:string;description:string;durationDays:number;durationNights:number;basePriceMinor:number;currency:string;status:string;destinations:string[];heroImageUrl:string;departures:Array<{id:string;code:string;startsOn:string;endsOn:string;capacity:number;confirmedCount:number;status:string}>};
export const dynamic="force-dynamic";
export default async function AdminTourPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const data=await getAdminJson<{items:Tour[]}>("/api/v1/admin/resources/tours");const tour=data.items.find((item)=>item.id===id);if(!tour)notFound();return <AdminShell activePath="/tours"><PageHeader eyebrow="Tour product" title={tour.name} description={tour.summary} actions={<TourPublishActions tourId={tour.id} status={tour.status} />} /><div className="tour-admin-grid"><section className="panel tour-admin-hero"><Image src={tour.heroImageUrl} width={900} height={460} alt={tour.name}/><div><StatusBadge tone={tour.status==="PUBLISHED"?"success":"warning"}>{tour.status}</StatusBadge><h2>{tour.description}</h2><p>{tour.durationDays} өдөр / {tour.durationNights} шөнө · {tour.destinations.join(", ")}</p><strong>{formatCurrencyMinor(tour.basePriceMinor,tour.currency)}</strong></div></section><section className="panel"><div className="panel__header"><h2>Хуваарьт гаралтууд</h2></div><div className="panel__body">{tour.departures.length===0?<p>Departure хараахан алга.</p>:tour.departures.map((departure)=><article className="admin-departure" key={departure.id}><div><strong>{departure.code}</strong><span>{departure.startsOn} → {departure.endsOn}</span></div><StatusBadge tone={departure.status==="DRAFT"?"warning":"success"}>{departure.status}</StatusBadge><span>{departure.confirmedCount}/{departure.capacity}</span></article>)}</div></section></div></AdminShell>}
