import Image from "next/image";
import { notFound } from "next/navigation";
import { AdminShell, PageHeader, StatusBadge } from "@toms/admin-ui";
import { formatCurrencyMinor } from "@toms/config";
import { TourPublishActions } from "@/components/tour-publish-actions";
import { getAdminJson } from "@/lib/api";
import { getServerI18n } from "@/lib/i18n";
import { intlLocale, statusLabel } from "@toms/i18n";
type Tour={id:string;name:string;slug:string;summary:string;description:string;durationDays:number;durationNights:number;basePriceMinor:number;currency:string;status:string;destinations:string[];heroImageUrl:string;departures:Array<{id:string;code:string;startsOn:string;endsOn:string;capacity:number;confirmedCount:number;status:string}>};
export const dynamic="force-dynamic";
export default async function AdminTourPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const { locale, t }=await getServerI18n();let tour:Tour;try{tour=await getAdminJson<Tour>(`/api/v1/admin/tours/${id}`)}catch{notFound()}return <AdminShell activePath="/tours"><PageHeader eyebrow={t("admin.tourProduct")} title={tour.name} description={tour.summary} actions={<TourPublishActions tourId={tour.id} status={tour.status} />} /><div className="tour-admin-grid"><section className="panel tour-admin-hero"><Image src={tour.heroImageUrl} width={900} height={460} alt={tour.name}/><div><StatusBadge tone={tour.status==="PUBLISHED"?"success":"warning"}>{statusLabel(locale,tour.status)}</StatusBadge><h2>{tour.description}</h2><p>{t("common.days",{count:tour.durationDays})} / {t("common.nights",{count:tour.durationNights})} · {tour.destinations.join(", ")}</p><strong>{formatCurrencyMinor(tour.basePriceMinor,tour.currency,intlLocale(locale))}</strong></div></section><section className="panel"><div className="panel__header"><h2>{t("admin.departures")}</h2></div><div className="panel__body">{tour.departures.length===0?<p>{t("admin.noDepartures")}</p>:tour.departures.map((departure)=><article className="admin-departure" key={departure.id}><div><strong>{departure.code}</strong><span>{departure.startsOn} → {departure.endsOn}</span></div><StatusBadge tone={departure.status==="DRAFT"?"warning":"success"}>{statusLabel(locale,departure.status)}</StatusBadge><span>{departure.confirmedCount}/{departure.capacity}</span></article>)}</div></section></div></AdminShell>}
