import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, CalendarDays, CheckCircle2, FileText, Users } from "lucide-react";
import { AdminShell, Button, Card, CardContent, CardHeader, CardTitle, PageHeader, Progress, StatusBadge, Tabs, TabsContent, TabsList, TabsTrigger } from "@toms/admin-ui";
import { getAdminJson } from "@/lib/api";
import { getServerI18n } from "@/lib/i18n";

type Departure = { id: string; code: string; tourName: string; startsOn: string; endsOn: string; confirmedCount: number; capacity: number; status: string; tripStatus: string; priceMinor: number; currency: string; riskCount?: number };
type Readiness = { overallPercent: number; checks: Array<{ id: string; label: string; status: string; percent: number }> };

export default async function DepartureDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { t } = await getServerI18n();
  let departure: Departure; let readiness: Readiness;
  try { [departure, readiness] = await Promise.all([getAdminJson<Departure>(`/api/v1/admin/departures/${id}`), getAdminJson<Readiness>(`/api/v1/admin/departures/${id}/readiness`)]); } catch { notFound(); }
  return <AdminShell activePath="/departures"><PageHeader eyebrow="DEPARTURE CONTROL" title={departure.code} description={`${departure.tourName} · ${departure.startsOn} → ${departure.endsOn}`} actions={<><Button variant="outline" render={<Link href={`/manifest?departureId=${departure.id}`} />}><Users /> Manifest</Button><Button>Update departure</Button></>} /><div className="detail-metric-grid"><Card><CardContent><CalendarDays /><span>Date range</span><strong>{departure.startsOn}<br />{departure.endsOn}</strong></CardContent></Card><Card><CardContent><Users /><span>Occupancy</span><strong>{departure.confirmedCount} / {departure.capacity}</strong><Progress value={departure.confirmedCount / departure.capacity * 100} /></CardContent></Card><Card><CardContent><CheckCircle2 /><span>Readiness</span><strong>{readiness.overallPercent}%</strong><Progress value={readiness.overallPercent} /></CardContent></Card><Card><CardContent><AlertTriangle /><span>Open risks</span><strong>{departure.riskCount ?? 0}</strong></CardContent></Card></div><Tabs defaultValue="readiness" className="detail-tabs"><TabsList><TabsTrigger value="readiness">Readiness</TabsTrigger><TabsTrigger value="inventory">Inventory</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger></TabsList><TabsContent value="readiness"><Card><CardHeader><CardTitle>Operational readiness</CardTitle><StatusBadge tone={readiness.overallPercent > 85 ? "success" : "warning"}>{readiness.overallPercent}% complete</StatusBadge></CardHeader><CardContent className="readiness-grid">{readiness.checks.map((check) => <article key={check.id}><span><FileText /><strong>{check.label}</strong><StatusBadge tone={check.status === "READY" ? "success" : check.status === "AT_RISK" ? "danger" : "warning"}>{check.status}</StatusBadge></span><Progress value={check.percent} /><small>{check.percent}% complete</small></article>)}</CardContent></Card></TabsContent><TabsContent value="inventory"><Card><CardContent><h2>{t("admin.capacity")}</h2><Progress value={departure.confirmedCount / departure.capacity * 100} /><p>{departure.capacity - departure.confirmedCount} seats remain available.</p></CardContent></Card></TabsContent><TabsContent value="documents"><Card><CardContent><h2>{t("nav.documents")}</h2><p>Traveler-visible documents and expiry checks are linked to this departure.</p></CardContent></Card></TabsContent><TabsContent value="timeline"><Card><CardContent><h2>Operations timeline</h2><p>Supplier, payment, document and itinerary milestones appear here.</p></CardContent></Card></TabsContent></Tabs></AdminShell>;
}
