import Link from "next/link";
import { ArrowRight, CheckCircle2, CreditCard, ReceiptText } from "lucide-react";
import { Button, Card, CardContent, Progress, StatusBadge, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@toms/storefront-ui";
import { formatCurrencyMinor } from "@toms/config";
import { getTripPayments } from "@/lib/api";
import { PortalShell } from "@/components/portal-shell";

export const dynamic = "force-dynamic";
export default async function PaymentsPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const data = await getTripPayments(id); const format = (amount: { amountMinor: number; currency: string }) => formatCurrencyMinor(amount.amountMinor, amount.currency, "mn-MN"); const paidPercent = data.total.amountMinor === 0 ? 0 : data.paid.amountMinor / data.total.amountMinor * 100; return <PortalShell activePath="/account/payments"><header className="portal-header"><div><p className="section-eyebrow">BOOKING FINANCE</p><h1>Payments</h1><p>Payment schedule, receipts and remaining balance.</p></div><StatusBadge tone={data.paymentStatus === "PAID" ? "success" : "warning"}>{data.paymentStatus}</StatusBadge></header><div className="portal-kpi-grid"><Card><CardContent><CreditCard /><span>Total</span><strong>{format(data.total)}</strong></CardContent></Card><Card><CardContent><CheckCircle2 /><span>Paid</span><strong>{format(data.paid)}</strong><Progress value={paidPercent} /></CardContent></Card><Card><CardContent><ReceiptText /><span>Balance due</span><strong>{format(data.due)}</strong>{data.due.amountMinor > 0 ? <Button>Pay balance<ArrowRight /></Button> : null}</CardContent></Card></div><section className="portal-payment-section"><h2>Payment schedule</h2><div className="payment-schedule">{data.schedule.map((item) => <Card key={item.id}><CardContent><StatusBadge tone={item.status === "PAID" ? "success" : item.status === "OVERDUE" ? "danger" : "warning"}>{item.status}</StatusBadge><span><strong>{item.label}</strong><small>Due {item.dueOn}</small></span><strong>{format(item.amount)}</strong></CardContent></Card>)}</div></section><section className="portal-payment-section"><h2>Transactions & receipts</h2><Card><CardContent><Table><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead><TableHead>Amount</TableHead><TableHead><span className="sr-only">Receipt</span></TableHead></TableRow></TableHeader><TableBody>{data.transactions.map((item) => <TableRow key={item.id}><TableCell><strong>{item.reference}</strong></TableCell><TableCell>{item.createdAt}</TableCell><TableCell><StatusBadge tone="success">{item.status}</StatusBadge></TableCell><TableCell>{format(item.amount)}</TableCell><TableCell><Button variant="link" render={<Link href="#receipt" />}>Receipt</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></section></PortalShell>; }
