import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Mail, MapPin, Phone } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger, Button } from "@toms/storefront-ui";

export type CmsPageData = { slug: string; title: string; blocks: Array<{ id: string; type: string; content: { title?: string; body?: string; imageUrl?: string } }> };
export function CmsBlocks({ page }: { page: CmsPageData }) { return <>{page.blocks.map((block) => block.type === "HERO" ? <header className="cms-hero" key={block.id}>{block.content.imageUrl ? <Image src={block.content.imageUrl} alt={block.content.title ?? page.title} fill priority sizes="100vw" /> : null}<div><p className="section-eyebrow">MUNKH DISCOVERY</p><h1>{block.content.title ?? page.title}</h1></div></header> : block.type === "IMAGE_TEXT" ? <section className="section story-split" key={block.id}><div className="page-container"><div className="story-split__image">{block.content.imageUrl ? <Image src={block.content.imageUrl} alt={block.content.title ?? "Munkh Discovery"} fill sizes="(max-width: 768px) 100vw, 50vw" /> : null}</div><div><p className="section-eyebrow">OUR STORY</p><h2>{block.content.title}</h2><p>{block.content.body}</p><Button variant="outline" render={<Link href="/tours" />}>Explore our journeys<ArrowRight /></Button></div></div></section> : null)}</>; }

export function ContactDetails() { return <section className="contact-details"><div><Mail /><span>Email</span><strong>travel@munkh.mn</strong></div><div><Phone /><span>Phone</span><strong>+976 7011 2233</strong></div><div><MapPin /><span>Studio</span><strong>Ulaanbaatar, Mongolia</strong></div></section>; }
export function ContactFaq() { const items = [{ q: "How far ahead should I book?", a: "For international journeys, three to six months gives the best choice of departures and flights." }, { q: "Can you tailor a private journey?", a: "Yes. Share your dates, group and interests, and our journey designers will respond with options." }, { q: "What happens after I book?", a: "Your traveler portal brings payments, documents, messages and the live itinerary into one place." }]; return <Accordion>{items.map((item, index) => <AccordionItem value={`faq-${index}`} key={item.q}><AccordionTrigger>{item.q}</AccordionTrigger><AccordionContent>{item.a}</AccordionContent></AccordionItem>)}</Accordion>; }
