import { Filter, Search } from "lucide-react";
import type { StorefrontToursResponse } from "@toms/contracts";
import { Button, Checkbox, Field, FieldLabel, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger, TourCard } from "@toms/storefront-ui";
import { getServerI18n } from "@/lib/i18n";

function Filters({ data, query }: { data: StorefrontToursResponse; query: string }) {
  return <form className="tour-filters" action="/tours"><Field><FieldLabel htmlFor="tour-search">Search journeys</FieldLabel><div className="filter-input"><Search /><Input id="tour-search" name="q" defaultValue={query} placeholder="Altai, Seoul, culture…" /></div></Field><fieldset><legend>Destination</legend>{data.facets.destinations.slice(0, 8).map((item) => <Field orientation="horizontal" key={item.value}><Checkbox id={`destination-${item.value}`} name="destination" value={item.value} /><FieldLabel htmlFor={`destination-${item.value}`}><span>{item.label}</span><small>{item.count}</small></FieldLabel></Field>)}</fieldset><fieldset><legend>Journey type</legend>{data.facets.categories.filter((item) => item.count > 0).map((item) => <Field orientation="horizontal" key={item.value}><Checkbox id={`category-${item.value}`} name="category" value={item.value} /><FieldLabel htmlFor={`category-${item.value}`}><span>{item.label}</span><small>{item.count}</small></FieldLabel></Field>)}</fieldset><Button type="submit">Apply filters</Button></form>;
}

export async function TourExplorer({ data, query = "" }: { data: StorefrontToursResponse; query?: string }) {
  const { t } = await getServerI18n();
  return <div className="tour-list-layout"><aside className="filter-rail"><Filters data={data} query={query} /></aside><section className="tour-results"><div className="results-toolbar"><span>{t("public.tourCount", { count: data.page.total })}</span><Sheet><SheetTrigger render={<Button className="mobile-filter" variant="outline" />}><Filter />Filters</SheetTrigger><SheetContent side="left"><SheetHeader><SheetTitle>Find your journey</SheetTitle><SheetDescription>Filter by destination and style.</SheetDescription></SheetHeader><Filters data={data} query={query} /></SheetContent></Sheet><Select defaultValue="featured"><SelectTrigger aria-label="Sort tours"><SelectValue /></SelectTrigger><SelectContent>{data.sortOptions.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>{data.items.length === 0 ? <div className="empty-results"><Search /><h2>No journeys found</h2><p>Try a broader destination or remove a filter.</p></div> : <div className="tour-list-grid">{data.items.map((tour) => <TourCard key={tour.id} tour={{ slug: tour.slug, name: tour.name, summary: tour.summary, heroImageUrl: tour.heroImage.url, durationDays: tour.durationDays, priceMinor: tour.priceFrom.amountMinor, currency: tour.priceFrom.currency, destination: tour.destinations.join(" · "), nextAvailableOn: tour.nextAvailableOn, availabilityLabel: tour.availabilityLabel, promotionLabel: tour.promotion?.label ?? null }} />)}</div>}<div className="catalog-pagination"><Button variant="outline" disabled={data.page.page <= 1}>Previous</Button><span>Page {data.page.page} of {Math.max(1, data.page.pageCount)}</span><Button variant="outline" disabled={data.page.page >= data.page.pageCount}>Next</Button></div></section></div>;
}
