import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgePercent, CalendarDays } from "lucide-react";
import { Badge, Button, Card, CardContent } from "@toms/storefront-ui";
import { getPromotions } from "@/lib/api";
import { getServerI18n } from "@/lib/i18n";

type Promotion = { id: string; code: string; name: string; description: string; benefit: string; status: string; startsAt: string; endsAt: string };
export const dynamic = "force-dynamic";
export default async function PromotionsPage() { const [data, { t }] = await Promise.all([getPromotions<{ items: Promotion[]; featured: Promotion | null }>(), getServerI18n()]); const featured = data.featured; return <main><header className="campaign-hero"><Image src="/images/seoul.png" alt="Seoul city at dusk" fill priority sizes="100vw" /><div><p className="section-eyebrow">LIMITED OFFERS</p><h1>{t("nav.promotions")}</h1><p>{t("promotions.publicDescription")}</p>{featured ? <Button size="lg" render={<Link href="/tours?promotion=active" />}>Explore eligible journeys<ArrowRight /></Button> : null}</div></header><section className="section"><div className="page-container">{featured ? <div className="featured-offer"><div><Badge variant="secondary">FEATURED OFFER</Badge><h2>{featured.name}</h2><p>{featured.description}</p><strong>{featured.benefit}</strong><div><CalendarDays />Valid until {featured.endsAt.slice(0, 10)}</div></div><div className="offer-code"><BadgePercent /><span>Use code</span><strong>{featured.code}</strong></div></div> : null}<header className="section-header"><div><p className="section-eyebrow">ACTIVE NOW</p><h2>Offers worth planning around</h2></div></header><div className="offer-grid">{data.items.map((item) => <Card key={item.id}><CardContent><Badge variant="secondary">{item.status}</Badge><h3>{item.name}</h3><p>{item.description}</p><strong>{item.benefit}</strong><span>{item.startsAt.slice(0, 10)} → {item.endsAt.slice(0, 10)}</span><div className="offer-code-small">{item.code}</div><Button variant="outline" render={<Link href="/tours" />}>View journeys<ArrowRight /></Button></CardContent></Card>)}</div><section className="promotion-terms"><h2>Offer terms</h2><p>Offers apply only to eligible published departures and are validated during checkout. Inventory and booking deadlines remain authoritative.</p></section></div></section></main>; }
