import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarDays, CreditCard, FileText, MessageSquare } from "lucide-react";
import { Alert, AlertDescription, AlertTitle, Button, Card, CardContent, Progress, StatusBadge } from "@toms/storefront-ui";
import { formatCurrencyMinor } from "@toms/config";
import { getTravelerDashboard } from "@/lib/api";
import { getServerI18n } from "@/lib/i18n";
import { PortalShell } from "@/components/portal-shell";

export const dynamic = "force-dynamic";
export default async function AccountPage() { const [data, { locale }] = await Promise.all([getTravelerDashboard(), getServerI18n()]); const trip = data.currentTrip; return <PortalShell activePath="/account"><header className="portal-header"><div><p className="section-eyebrow">TRAVELER PORTAL</p><h1>Welcome back, Bat</h1><p>Everything needed for your next journey, in one place.</p></div></header>{trip ? <><section className="current-trip"><Image src={trip.trip.heroImageUrl} alt={trip.trip.tourName} fill priority sizes="(max-width: 768px) 100vw, 70vw" /><div><StatusBadge tone="success">{trip.booking.status}</StatusBadge><p>DEPARTING IN <strong>{trip.trip.daysUntilDeparture} DAYS</strong></p><h2>{trip.trip.tourName}</h2><span><CalendarDays />{trip.trip.startsOn} → {trip.trip.endsOn}</span><Button render={<Link href={`/account/trips/${trip.booking.id}`} />}>Open trip<ArrowRight /></Button></div></section><div className="portal-kpi-grid"><Card><CardContent><span>Overall readiness</span><strong>{trip.readiness.overallPercent}%</strong><Progress value={trip.readiness.overallPercent} /></CardContent></Card><Card><CardContent><CreditCard /><span>Balance due</span><strong>{formatCurrencyMinor(trip.paymentSummary.dueMinor, trip.paymentSummary.currency, locale === "mn" ? "mn-MN" : "en-US")}</strong><Button variant="link" render={<Link href={`/account/trips/${trip.booking.id}/payments`} />}>View payments</Button></CardContent></Card><Card><CardContent><FileText /><span>Documents</span><strong>{trip.documentSummary.ready} / {trip.documentSummary.required} ready</strong><Button variant="link" render={<Link href={`/account/trips/${trip.booking.id}/documents`} />}>Open documents</Button></CardContent></Card></div><div className="portal-dashboard-grid"><section><h2>Required actions</h2><div className="action-list">{trip.actionsRequired.map((action) => <Alert key={action.href} variant={action.severity === "CRITICAL" ? "destructive" : "default"}><AlertTriangle /><AlertTitle>{action.title}</AlertTitle><AlertDescription><Button variant="link" render={<Link href={action.href} />}>Resolve now<ArrowRight /></Button></AlertDescription></Alert>)}</div></section><section><h2>Latest message</h2>{data.latestMessage ? <Card><CardContent className="latest-message"><MessageSquare /><span><strong>{data.latestMessage.subject}</strong><p>{data.latestMessage.preview}</p><small>{data.latestMessage.createdAt}</small></span><Button variant="outline" render={<Link href="/account/messages" />}>Open inbox</Button></CardContent></Card> : <p>No new messages.</p>}</section></div></> : <div className="portal-empty"><h2>No upcoming trips</h2><p>Your confirmed journeys will appear here.</p><Button render={<Link href="/tours" />}>Explore journeys</Button></div>}</PortalShell>; }
